config/routes.rb
Rails.application.routes.draw do
  root to: "artists#index"

  devise_for :users
  resources :artists
  resources :songs
  resources :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_many :photos, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, allow_blank: true, length: { maximum: 500 }

  def self.order_by_name
    order :first_name
  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist

  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.all
  end

  def show
    @photos = @artist.photos
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      image_params.each do |image|
        @artist.photos.create(image: image)
      end

      redirect_to @artist, notice: "Artist is successfully created"
    else
      render 'new'
    end
  end

  def edit
    @photos = @artist.photos
  end

  def update
    if @artist.update(artist_params)
      image_params.each do |image|
        @artist.photos.create(image: image)
      end

      redirect_to edit_artist_path(@artist), notice: "Artist is successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to root_path, notice: "Artist is successfully removed"
  end

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:first_name, :last_name, :bio)
  end

  def image_params
    params[:images].present? ? params.require(:images) : []
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @artist = photo.artist
    photo.destroy
    redirect_to edit_artist_path(@artist), notice: "Photo successfully removed"
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :destroy]

  def index
    @songs = Song.all
  end

  def show; end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to root_path, notice: "Song is successfully created"
    else
      render "new"
    end
  end

  def destroy
    @song.destroy
    redirect_to root_path, notice: "Song is successfully removed"
  end

  private

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title, :artist_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist, html: { multipart: true } do |f| %>
  <%= render 'shared/validation_errors' %>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :bio %>
    <%= f.text_field :bio, placeholder: "Biography", class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="photos">Photos</label>
    <span class="btn btn-default">
    Upload Photos
    <%= file_field_tag "images[]", type: :file, multiple: true %>
    </span>
  </div>

  <div id="photos">
    <%= render 'photos/list' %>
  </div>

  <div class="actions">
    <%= f.submit (@artist.new_record? ? "CREATE" : "UPDATE"), class: "btn btn-info" %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Edit artist</h2>
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

<p><%= link_to "BACK", artists_path, class: "btn btn-default"%></p>

app/views/artists/index.html.erb
<div class="row">
  <p> <%= link_to "+ CREATE NEW ARTIST", new_artist_path, class: "btn btn-info" %> </p>
  <% @artists.each do |artist| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <% artist.photos.each do |photo| %>
          <%= image_tag photo.image.thumbnail %>
        <% end %>
        <div class="caption">
          <h3><%= link_to artist.first_name, artist %></h3>
          <h4><%= link_to artist.last_name, artist %> </h4>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/artists/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Add a new artist</h2>
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

<p><%= link_to "BACK", artists_path, class: "btn btn-default"%></p>

app/views/artists/show.html.erb
<div class="row">
<!-- artist's photo -->
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <% @artist.photos.each do |photo| %>
        <%= image_tag photo.image.thumbnail %>
      <% end %>
    </div>
  </div>

<!-- Artist's main info -->
  <div class="col-md-6 col-md-4">
    <div class="caption">
      <h3><label for="first_name"> First Name: <%= @artist.first_name %></h3>
      <h4><label for="last_name"> Last Name: <%= @artist.last_name %></h4>
      <p><label for="bio"> Bio: </label> <%= @artist.bio %></p>

<!-- List of songs -->
      <h3>List of Songs</h3>
      <% if @artist.songs.any? %>
        <ul>
          <% @artist.songs.each do |song| %>
            <li><%= song.title %>
            <%= link_to "[Delete]", song_path(song.id), method: :delete, data: { confirm: "Are you sure?" } %></li>
          <% end %>
        </ul>
      <% else %>
        <p>There are no songs for this artist.</p>
      <% end %>
    </div>
  </div>
</div>
  <hr/>

<p><%= link_to "+ ADD NEW SONG", new_song_path, class: "btn btn-info" %>
<%= link_to "EDIT ARTIST", edit_artist_path(@artist.id), class: "btn btn-warning"%>
<%= link_to "DELETE ARTIST", artist_path(@artist.id), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %></p>
<%= link_to "BACK", artists_path, class: "btn btn-default"%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <div class="container">
      <%if notice != nil %>
        <p class="alert alert-info"><%= notice %></p>
      <%end%>
      <%if alert != nil %>
        <p class="alert alert-danger"><%= alert %></p>
      <%end%>
      <%= yield %>
    </div>

  </body>
</html>

app/views/photos/_list.html.erb
<% if @photos %>
  <% @photos.each do |photo| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= image_tag photo.image %>
      </div>
      <div class="panel-body">
        <%= link_to "[Delete photo]", photo_path(photo.id), method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "codaisseurify", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_validation_errors.html.erb
<% if @song != nil %>
  <% @song.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>
<% end %>

<% if @artist != nil %>
  <% @artist.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>
<% end %>

app/views/songs/_form.html.erb
<%= form_for @song do |f| %>
  <%= render 'shared/validation_errors' %>

  <div class="form-group">
    <label for="title">Song Title</label>
    <%= f.text_field :title, placeholder: "Song Title", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :artist_id %>
    <%= f.collection_select(:artist_id, Artist.all, :id, :first_name) %>
  </div>

  <div class="actions">
    <%= f.submit "CREATE", class: "btn btn-default" %>
  </div>
<% end %>

app/views/songs/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Add a new song</h2>
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

<p> <%= link_to "+ CREATE NEW ARTIST", new_artist_path, class: "btn btn-info" %>
<%= link_to "BACK", artists_path, class: "btn btn-default"%></p>